# Generated by Django 5.2.12 on 2026-03-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("api_key", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField()),
                ("CPU", models.CharField(blank=True, max_length=255, null=True)),
                ("RAM", models.CharField(blank=True, max_length=255, null=True)),
                ("GPU", models.CharField(blank=True, max_length=255, null=True)),
                ("SWAP", models.CharField(blank=True, max_length=255, null=True)),
                ("DISK", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
