# Generated by Django 5.2.12 on 2026-03-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
