# Generated by Django 5.2.12 on 2026-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Server", "0002_alter_server_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="MAX_CPU",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="MAX_DISK",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="MAX_GPU",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="MAX_RAM",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="MAX_SWAP",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
