# Generated by Django 5.2.12 on 2026-03-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Server", "0003_server_max_cpu_server_max_disk_server_max_gpu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="List_Ssh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("ip", models.GenericIPAddressField()),
                ("port", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("full_message_log", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="server",
            old_name="CPU",
            new_name="CPU_NAME",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="DISK",
            new_name="DISK_NAME",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="GPU",
            new_name="GPU_NAME",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="MAX_CPU",
            new_name="GPU_SIZE_GB",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="MAX_GPU",
            new_name="MAX_GPU_THREADS",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="RAM",
            new_name="RAM_CHARACTERISTICS",
        ),
        migrations.RemoveField(
            model_name="server",
            name="SWAP",
        ),
        migrations.AddField(
            model_name="server",
            name="MAX_CPU_CORES",
            field=models.CharField(
                blank=True,
                help_text="Максимальное количество ядер CPU",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="MAX_CPU_THREADS",
            field=models.CharField(
                blank=True,
                help_text="Максимальное количество потоков CPU",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="MAX_DISK",
            field=models.CharField(
                blank=True,
                help_text="Максимальный объем дискового пространства",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="MAX_SWAP",
            field=models.CharField(
                blank=True,
                help_text="Максимальный объем SWAP памяти",
                max_length=255,
                null=True,
            ),
        ),
    ]
