# Generated by Django 5.2.12 on 2026-03-26 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu", models.FloatField(help_text="CPU(%)")),
                ("ram", models.FloatField(help_text="RAM(%)")),
                (
                    "IO",
                    models.FloatField(
                        blank=True, help_text="Input/Output(%)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Server.server"
                    ),
                ),
            ],
        ),
    ]
