# Generated by Django 5.2.12 on 2026-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Metric", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverstat",
            name="Cpu_Info",
            field=models.IntegerField(
                blank=True, help_text="Total CPU Cores", null=True
            ),
        ),
    ]
